[tool.poetry]
name = "nhs-gpu"
version = "0.1.0"
description = "NHS GPU environment with transformers + sentence-transformers"
authors = ["Mark"]

[tool.poetry.dependencies]
python = "3.11.4"

torch = { version = "2.5.1+cu121", source = "pytorch-cu121" }
torchvision = { version = "0.20.1+cu121", source = "pytorch-cu121" }
torchaudio = { version = "2.5.1+cu121", source = "pytorch-cu121" }

transformers = "^4.45.0"
tokenizers = "^0.20.0"
huggingface-hub = "*"
sentence-transformers = "^3.0"

ipykernel = "^6.29.0"
jupyter = "^1.0.0"
pandas = "^3.0.5"
faiss-cpu = "^1.15.0"
datasets = "^5.0.1"
accelerate = "^1.14.0"
shap = "0.41.0"
matplotlib = "^3.11.1"
seaborn = "^0.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[[tool.poetry.source]]
name = "pypi"
priority = "default"